DROP TABLE IF EXISTS T_POST;

CREATE TABLE `T_POST` (
  	`POST_ID` int(11) NOT NULL AUTO_INCREMENT,
	`TITLE` varchar(100) NOT NULL,
	`USER_ID` int(11) NOT NULL,
  	`CONTENTS` text NOT NULL,
  	`REG_DATE` datetime NOT NULL,
  	PRIMARY KEY (`POST_ID`)
);

DROP TABLE IF EXISTS T_USER;

CREATE TABLE `T_USER` (
  	`USER_ID` int(11) NOT NULL AUTO_INCREMENT,
	`EMAIL` text NOT NULL,
	`PASSWORD` varchar(100) NOT NULL,
	`ROLE` varchar(100) NOT NULL,
	`REG_DATE` datetime NOT NULL,
  	PRIMARY KEY (`USER_ID`)
);
