DROP TABLE IF EXISTS T_POST;

CREATE TABLE `T_POST` (
  	`POST_ID` int(11) NOT NULL AUTO_INCREMENT,
	`TITLE` varchar(100) NOT NULL,
	`USER_ID` int(11) NOT NULL,
  	`CONTENTS` text NOT NULL,
  	`REG_DATE` datetime NOT NULL,
  	PRIMARY KEY (`POST_ID`)
)
